
FP_ERROR_CODE_GENERIC_OVERFLOW  = 0
FP_ERROR_CODE_DIVISION_BY_ZERO  = 1
FP_ERROR_CODE_LOG_DOMAIN_ERROR  = 2
FP_ERROR_CODE_EXPONENT_OVERFLOW = 3
FP_ERROR_CODE_IEEE754_INF       = 4
FP_ERROR_CODE_IEEE754_NAN       = 5
